export const ADD_ANIME = 'ADD_ANIME'
export const UPDATE_ANIME = 'UPDATE_ANIME'

export const ANIME_REQUEST = 'ANIME_REQUEST'
export const ANIME_SUCCESS = 'ANIME_SUCCESS'
export const ANIME_FAILURE = 'ANIME_FAILURE'
