export const GRAPHQL_REQUEST = 'GRAPHQL_REQUEST'
export const GRAPHQL_SUCCESS = 'GRAPHQL_SUCCESS'

export const ADD_ANIME = 'ADD_ANIME'
export const UPDATE_ANIME = 'UPDATE_ANIME'
export const ANIME_REQUEST = 'ANIME_REQUEST'
export const ANIME_LOAD = 'ANIME_LOAD'
export const ANIME_SUCCESS = 'ANIME_SUCCESS'
export const ANIME_FAILURE = 'ANIME_FAILURE'

export const ADD_MANGA = 'ADD_MANGA'
export const UPDATE_MANGA = 'UPDATE_MANGA'
export const MANGA_LOAD = 'MANGA_LOAD'

export const ADD_TAG = 'ADD_TAG'

export const TAGS_REQUEST = 'TAGS_REQUEST'
export const TAGS_LOAD = 'TAGS_LOAD'
export const TAGS_SUCCESS = 'TAGS_SUCCESS'
export const TAGS_FAILURE = 'TAGS_FAILURE'

export const EPISODE_REQUEST = 'EPISODE_REQUEST'
export const EPISODE_LOAD = 'EPISODE_LOAD'
export const EPISODE_REFRESH = 'EPISODE_REFRESH'
export const EPISODE_REMOVE = 'EPISODE_REMOVE'
export const EPISODE_SUCCESS = 'EPISODE_SUCCESS'

export const CHAPTER_REQUEST = 'CHAPTER_REQUEST'
export const CHAPTER_LOAD = 'CHAPTER_LOAD'
export const CHAPTER_REFRESH = 'CHAPTER_REFRESH'
export const CHAPTER_REMOVE = 'CHAPTER_REMOVE'
export const CHAPTER_SUCCESS = 'CHAPTER_SUCCESS'

export const TOGGLE_SORT = 'TOGGLE_SORT'
export const SET_SORT_KEY = 'SET_SORT_KEY'

export const SET_ITEMS_PER_PAGE = 'SET_ITEMS_PER_PAGE'
export const NEXT_PAGE = 'NEXT_PAGE'
export const PREV_PAGE = 'PREV_PAGE'
export const RESET_PAGE = 'RESET_PAGE'

export const TOGGLE_IS_ADULT = 'TOGGLE_IS_ADULT'

export const SET_THEME_CLASS = 'SET_THEME_CLASS'
export const TOGGLE_TIMED_THEME = 'TOGGLE_TIMED_THEME'

export const LOAD_PAGE_INFO = 'LOAD_PAGE_INFO'


export const TOGGLE_SIDEBAR_VISIBILITY = 'TOGGLE_SIDEBAR_VISIBILITY'
export const TOGGLE_SIDEBAR_COLLAPSE = 'TOGGLE_SIDEBAR_COLLAPSE
export const CLOSE_SIDEBAR = 'CLOSE_SIDEBAR'
